# Generated by Django 4.2 on 2023-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('congestion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('congestion_level', models.CharField(blank=True, max_length=255, null=True)),
                ('observed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'congestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CongestionStatics',
            fields=[
                ('congestion_statistics_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('congestion', models.JSONField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=225)),
                ('updated_at', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'congestion_statics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('location_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icon_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'location_category',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RealtimeCongestions',
        ),
    ]
