# Generated by Django 4.2 on 2023-07-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getApi', '0002_congestion_congestionstatics_locationcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCongestionStatistic',
            fields=[
                ('congestion_statistic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_congestion_statistic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyCongestionStatistic',
            fields=[
                ('congestion_statistic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('congestion_level', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_congestion_statistic',
                'managed': False,
            },
        ),
    ]
